[package]
name = "mappr"
version = "0.2.2"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
mac_oui = { version = "0.4.10", features = ["with-db"] }
pnet = "0.35.0"
anyhow = "1.0.99"
colored = "3.0.0"
rand = "0.9.2"
tokio = { version = "1.47.1", features = ["full"] }
is-root = "0.1.3"
indicatif = "0.18.0"
once_cell = "1.21.3"
sys-info = "0.9.1"
sysinfo = "0.37.2"
netstat2 = "0.11.2"
unicode-width = "0.2.2"