[workspace]
resolver = "2"
members = [
    "cli",
    "core",
    "common",
    "protocols",
    "plugins",
]

[workspace.dependencies]
anyhow = "1.0.99"
tokio = { version = "1.47.1", features = ["full"] }
async-trait = "0.1.86"
colored = "3.0.0"
clap = { version = "4.5.45", features = ["derive"] }
pnet = "0.35.0"
rand = "0.9.2"
indicatif = "0.18.0"
console = "0.16.1"
thiserror = "2.0.11"
crossterm = "0.29.0"
rayon = "1.11.0"
tracing = "0.1.44"

mappr-core = { path = "./core" }
mappr-common = { path = "./common" }
mappr-protocols = { path = "./protocols" }
mappr-plugins = { path = "./plugins" }