[package]
name = "zond-protocols"
version = "0.1.2"
edition = "2024"

[dependencies]
dns-parser = "0.8"
zond-common = { workspace = true }
pnet = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }

